/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import controle.Sobredao;
import funcionario.*;
import controle.Vendadao;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Victor
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //Mostrar o ano
        Calendar cal = Calendar.getInstance();
        Ano.setText("BControl © " + cal.get(Calendar.YEAR));
        limpar();

    }

    public void limpar() {
        visualizar();
    }

    public void visualizar() {
        DecimalFormat mt = new DecimalFormat("#,###,##0.00 Mt");
        DecimalFormat ud = new DecimalFormat("##0 Und");
        DefaultTableModel modelo = (DefaultTableModel) jTableproductos.getModel();
        modelo.setNumRows(0);
        Vendadao ndao = new Vendadao();
        ndao.visualizar().forEach((n) -> {
            modelo.addRow(new Object[]{
                n.getCodigo(),
                n.getNome(),
                ud.format(n.getQuantidade()),
                mt.format(n.getPreco()),
                n.getFuncionario(),
                n.getData()
            });
        });
        total.setText(mt.format(ndao.total()) + "");
    }

    public void procurar(String data, String data1) {
        DecimalFormat mt = new DecimalFormat("#,###,##0.00 Mt");
        DecimalFormat ud = new DecimalFormat("##0 Und");
        DefaultTableModel modelo = (DefaultTableModel) jTableproductos.getModel();
        modelo.setNumRows(0);
        Vendadao ndao = new Vendadao();
        ndao.procurar(data, data1).forEach((n) -> {
            modelo.addRow(new Object[]{
                n.getCodigo(),
                n.getNome(),
                ud.format(n.getQuantidade()),
                mt.format(n.getPreco()),
                n.getFuncionario(),
                n.getData()
            });
        });
        total.setText(mt.format(ndao.procurartotal(data, data1)) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conteudo = new javax.swing.JPanel();
        Separador = new javax.swing.JSeparator();
        Nome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproductos = new javax.swing.JTable();
        btnlimpar = new javax.swing.JButton();
        btnprocurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnsair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnrelatorio = new javax.swing.JButton();
        data = new com.toedter.calendar.JDateChooser();
        data1 = new com.toedter.calendar.JDateChooser();
        Rodape = new javax.swing.JToolBar();
        Ano = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBControl = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemVendasF = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenu();
        jMenuItemVisualizarP = new javax.swing.JMenuItem();
        jMenuItemAdicionarP = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuItemVisualizarF = new javax.swing.JMenuItem();
        jMenuItemAdicionarF = new javax.swing.JMenuItem();
        jMenuCupom = new javax.swing.JMenu();
        jMenuItemVisualizarC = new javax.swing.JMenuItem();
        jMenuItemAdicionarC = new javax.swing.JMenuItem();
        jMenuMais = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemEditarSenha = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Conteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Conteudo.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1360, 10));

        Nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nome.setText("Nome");
        Conteudo.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1030, -1));

        jTableproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Nome", "Quantidade", "Preço", "Funcionário", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproductosMouseClicked(evt);
            }
        });
        jTableproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableproductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproductos);
        if (jTableproductos.getColumnModel().getColumnCount() > 0) {
            jTableproductos.getColumnModel().getColumn(0).setResizable(false);
            jTableproductos.getColumnModel().getColumn(2).setResizable(false);
            jTableproductos.getColumnModel().getColumn(2).setPreferredWidth(11);
            jTableproductos.getColumnModel().getColumn(5).setResizable(false);
            jTableproductos.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        Conteudo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1340, 570));

        btnlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/actualizar.png"))); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        Conteudo.add(btnlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 110, 50));

        btnprocurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/procurar.png"))); // NOI18N
        btnprocurar.setText("Procurar");
        btnprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocurarActionPerformed(evt);
            }
        });
        Conteudo.add(btnprocurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Data (AAAA-MM-DD)");
        Conteudo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnsair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsair.setText("Sair");
        btnsair.setPreferredSize(new java.awt.Dimension(125, 25));
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        Conteudo.add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Data Fim (AAAA-MM-DD)");
        Conteudo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 140, -1));

        btnrelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/relatorio.png"))); // NOI18N
        btnrelatorio.setText("Relatório");
        btnrelatorio.setMaximumSize(new java.awt.Dimension(63, 23));
        btnrelatorio.setMinimumSize(new java.awt.Dimension(63, 23));
        btnrelatorio.setPreferredSize(new java.awt.Dimension(63, 23));
        btnrelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrelatorioActionPerformed(evt);
            }
        });
        Conteudo.add(btnrelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 110, 50));

        data.setDateFormatString("yyyy-MM-dd");
        Conteudo.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 30));

        data1.setDateFormatString("yyyy-MM-dd");
        Conteudo.add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 30));

        getContentPane().add(Conteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 690));

        Rodape.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rodape.setRollover(true);

        Ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rodape.add(Ano);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("   |   Total:   ");
        Rodape.add(jLabel8);

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("0.00 Mt");
        Rodape.add(total);

        getContentPane().add(Rodape, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1370, 40));

        jMenuBControl.setText("BControl");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuBControl.add(jMenuItemSair);
        jMenuBControl.add(jSeparator1);

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuBControl.add(jMenuItemFechar);

        jMenuBar1.add(jMenuBControl);

        jMenuRelatorio.setText("Relatório");

        jMenuItemProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mercadoria.png"))); // NOI18N
        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemProductos);

        jMenuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/funcionario.png"))); // NOI18N
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemClientes);

        jMenuItemVendasF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVendasF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pagar.png"))); // NOI18N
        jMenuItemVendasF.setText("Vendas");
        jMenuItemVendasF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasFActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemVendasF);

        jMenuBar1.add(jMenuRelatorio);

        jMenuProducto.setText("Producto");

        jMenuItemVisualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/info.png"))); // NOI18N
        jMenuItemVisualizarP.setText("Visualizar");
        jMenuItemVisualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarPActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItemVisualizarP);

        jMenuItemAdicionarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar.png"))); // NOI18N
        jMenuItemAdicionarP.setText("Adicionar");
        jMenuItemAdicionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarPActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItemAdicionarP);

        jMenuBar1.add(jMenuProducto);

        jMenuFuncionario.setText("Funcionário");

        jMenuItemVisualizarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/info.png"))); // NOI18N
        jMenuItemVisualizarF.setText("Visualizar");
        jMenuItemVisualizarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarFActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemVisualizarF);

        jMenuItemAdicionarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar.png"))); // NOI18N
        jMenuItemAdicionarF.setText("Adicionar");
        jMenuItemAdicionarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarFActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemAdicionarF);

        jMenuBar1.add(jMenuFuncionario);

        jMenuCupom.setText("Cupom");

        jMenuItemVisualizarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/info.png"))); // NOI18N
        jMenuItemVisualizarC.setText("Visualizar");
        jMenuItemVisualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarCActionPerformed(evt);
            }
        });
        jMenuCupom.add(jMenuItemVisualizarC);

        jMenuItemAdicionarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar.png"))); // NOI18N
        jMenuItemAdicionarC.setText("Adicionar");
        jMenuItemAdicionarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarCActionPerformed(evt);
            }
        });
        jMenuCupom.add(jMenuItemAdicionarC);

        jMenuBar1.add(jMenuCupom);

        jMenuMais.setText("Mais");

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sobre.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre Nós");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuMais.add(jMenuItemSobre);

        jMenuItemEditarSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/editar.png"))); // NOI18N
        jMenuItemEditarSenha.setText("Editar Senha");
        jMenuItemEditarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarSenhaActionPerformed(evt);
            }
        });
        jMenuMais.add(jMenuItemEditarSenha);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/definicoes.png"))); // NOI18N
        jMenuItem1.setText("Reiniciar Sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuMais.add(jMenuItem1);

        jMenuBar1.add(jMenuMais);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void jTableproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableproductosKeyReleased

    }//GEN-LAST:event_jTableproductosKeyReleased

    private void jTableproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproductosMouseClicked

    }//GEN-LAST:event_jTableproductosMouseClicked

    private void btnprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocurarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String txtdata = sdf.format(data.getDate());
        String txtdata1 = sdf.format(data1.getDate());
        procurar(txtdata, txtdata1);
    }//GEN-LAST:event_btnprocurarActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        Inicio Inicio = new Inicio();
        Inicio.setVisible(true);
        limpar();
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemVisualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarPActionPerformed
        Producto Producto = new Producto();
        Producto.setVisible(true);
        Producto.pack();
        Producto.setLocationRelativeTo(null);
        Producto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemVisualizarPActionPerformed

    private void jMenuItemVisualizarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarFActionPerformed
        Funcionario Funcionario = new Funcionario();
        Funcionario.setVisible(true);
        Funcionario.pack();
        Funcionario.setLocationRelativeTo(null);
        Funcionario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemVisualizarFActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        Inicio Inicio = new Inicio();
        Inicio.setVisible(true);
        limpar();
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void jMenuItemAdicionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarPActionPerformed
        AdicionarP c = new AdicionarP();
        c.setVisible(true);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAdicionarPActionPerformed

    private void jMenuItemAdicionarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarFActionPerformed
        AdicionarF c = new AdicionarF();
        c.setVisible(true);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAdicionarFActionPerformed

    private void jMenuItemVisualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarCActionPerformed
        Cupom Cupom = new Cupom();
        Cupom.setVisible(true);
        Cupom.pack();
        Cupom.setLocationRelativeTo(null);
        Cupom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemVisualizarCActionPerformed

    private void jMenuItemAdicionarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarCActionPerformed
        AdicionarC Cupom = new AdicionarC();
        Cupom.setVisible(true);
        Cupom.pack();
        Cupom.setLocationRelativeTo(null);
        Cupom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAdicionarCActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        Productos Producto = new Productos();
        Producto.setVisible(true);
        Producto.pack();
        Producto.setLocationRelativeTo(null);
        Producto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
        cliente.pack();
        cliente.setLocationRelativeTo(null);
        cliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void btnrelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrelatorioActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String txtdata = sdf.format(data.getDate());
        String txtdata1 = sdf.format(data1.getDate());
        Vendadao ndao = new Vendadao();

        JasperPrint jasperPrint = null;

        JRResultSetDataSource rel = new JRResultSetDataSource((ResultSet) ndao.relatorioVendas(txtdata, txtdata1));
        HashMap params = new HashMap<>();

        //Passândo parâmetros e convertendo o dados pra ser compativel
        params.put("dataInicio", txtdata);
        params.put("dataFim", txtdata1);
        Sobredao sdao = new Sobredao();
        sdao.visualizar().forEach((s) -> {
            params.put("nomeLoja", s.getNome());
        });

        try {
            jasperPrint = JasperFillManager.fillReport("report/RelatorioVendas.jasper", params, rel);
            String data = new SimpleDateFormat("dd MM yyyy_HH mm ss").format(Calendar.getInstance().getTime());
            JasperExportManager.exportReportToPdfFile(jasperPrint, "C:\\Users\\" + System.getProperty("user.name") + "\\Documents\\BControl\\Vendas(" + data + ").pdf");
        } catch (JRException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(false);

    }//GEN-LAST:event_btnrelatorioActionPerformed

    private void jMenuItemEditarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarSenhaActionPerformed
        Senha Senha = new Senha();
        Senha.setVisible(true);
        Senha.pack();
        Senha.setLocationRelativeTo(null);
        Senha.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Senha.nome(Nome.getText());
    }//GEN-LAST:event_jMenuItemEditarSenhaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        Sobre Sobre = new Sobre();
        Sobre.setVisible(true);
        Sobre.pack();
        Sobre.setLocationRelativeTo(null);
        Sobre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Tem certeza que quer Reiniciar o Sistema?\nEste processo não tem volta.", "Reiniciar Sistema", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            Sobredao udao = new Sobredao();
            try {
                udao.reiniciar();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemVendasFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasFActionPerformed
        Vendas Venda = new Vendas();
        Venda.setVisible(true);
        Venda.pack();
        Venda.setLocationRelativeTo(null);
        Venda.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemVendasFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ano;
    private javax.swing.JPanel Conteudo;
    private javax.swing.JLabel Nome;
    private javax.swing.JToolBar Rodape;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnprocurar;
    private javax.swing.JButton btnrelatorio;
    private javax.swing.JButton btnsair;
    private com.toedter.calendar.JDateChooser data;
    private com.toedter.calendar.JDateChooser data1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuBControl;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCupom;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAdicionarC;
    private javax.swing.JMenuItem jMenuItemAdicionarF;
    private javax.swing.JMenuItem jMenuItemAdicionarP;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEditarSenha;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemVendasF;
    private javax.swing.JMenuItem jMenuItemVisualizarC;
    private javax.swing.JMenuItem jMenuItemVisualizarF;
    private javax.swing.JMenuItem jMenuItemVisualizarP;
    private javax.swing.JMenu jMenuMais;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTableproductos;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
 public void nome(String USUARIO) {
        Nome.setText(USUARIO);
    }
}
