/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcionario;

import controle.Numero;
import controle.Productodao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Adicionar extends javax.swing.JFrame {

    /**
     * Creates new form Adicionar
     */
    public Adicionar() {
        initComponents();
        txtquantidade.setDocument(new Numero());
        Quantidade.setVisible(false);
        Preco.setVisible(false);
    }

    public JButton getBtnadicionar() {
        return btnadicionar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadicionar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        Quantidade = new javax.swing.JLabel();
        Preco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Producto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Código:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Quantidade:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        btnadicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar.png"))); // NOI18N
        btnadicionar.setText("Adicionar");
        btnadicionar.setPreferredSize(new java.awt.Dimension(80, 30));
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, 50));

        txtnome.setEnabled(false);
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));
        jPanel1.add(txtquantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        txtcodigo.setEnabled(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 30));
        jPanel1.add(Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 40, -1));
        jPanel1.add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 70, 0));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        if (txtquantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha a Quantidade do Producto.", "Campo em branco", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.parseInt(txtquantidade.getText()) <= 0 || Integer.parseInt(txtquantidade.getText()) > Integer.parseInt(Quantidade.getText())) {
            txtquantidade.setText("");
            JOptionPane.showMessageDialog(null, "Por favor, preencha uma Quantidade válida.", "Quantidade indisponível", JOptionPane.WARNING_MESSAGE);
        } else {
            Productodao udao = new Productodao();

            try {
                if (udao.adicionar(txtcodigo.getText(), txtnome.getText(), Integer.parseInt(txtquantidade.getText()), (Integer.parseInt(txtquantidade.getText()) * Double.parseDouble(Preco.getText())))) {
                    udao.reduzir(txtcodigo.getText(), (Integer.parseInt(Quantidade.getText()) - Integer.parseInt(txtquantidade.getText())));
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao Adicionar.", "Desculpa", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(Adicionar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

    }//GEN-LAST:event_txtcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Preco;
    public javax.swing.JLabel Quantidade;
    private javax.swing.JButton btnadicionar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtnome;
    public javax.swing.JTextField txtquantidade;
    // End of variables declaration//GEN-END:variables

}
