/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcionario;

import controle.Usuariodao;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Senha extends javax.swing.JFrame {

    /**
     * Creates new form Senha
     */
    public Senha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnalterar = new javax.swing.JButton();
        txtsenha1 = new javax.swing.JPasswordField();
        txtactual = new javax.swing.JPasswordField();
        txtsenha = new javax.swing.JPasswordField();
        Nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 300));
        setPreferredSize(new java.awt.Dimension(240, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Senha Actual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nova Senha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Confirmar Nova Senha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        btnalterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/editar.png"))); // NOI18N
        btnalterar.setText("Alterar Senha");
        btnalterar.setPreferredSize(new java.awt.Dimension(80, 30));
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, 50));

        txtsenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        txtactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactualActionPerformed(evt);
            }
        });
        getContentPane().add(txtactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 30));

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        Usuariodao udao = new Usuariodao();

        String n = (String) Nome.getText();

        if (txtsenha.getText().equals("") || txtsenha1.getText().equals("") || txtactual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo em branco.", "Campo em branco", JOptionPane.WARNING_MESSAGE);

        } else if (txtsenha.getText().equals(txtsenha1.getText())) {
            try {
                if (udao.verificar(n, txtactual.getText())) {
                    if (udao.editar(n, txtsenha.getText())) {
                        JOptionPane.showMessageDialog(null, "Senha alterada.", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Não foi possível alterar a sua Senha.", "Desculpa", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    txtactual.setText("");
                    JOptionPane.showMessageDialog(null, "Senha Actual incorrecta.", "Desculpa", JOptionPane.ERROR_MESSAGE);
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            txtsenha.setText("");
            txtsenha1.setText("");
            JOptionPane.showMessageDialog(null, "Por favor, confirme a sua Nova Senha.", "Nova Senha incompatível", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void txtsenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenha1ActionPerformed

    private void txtactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtactualActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JButton btnalterar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtactual;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha1;
    // End of variables declaration//GEN-END:variables
public void nome(String USUARIO) {
        Nome.setText(USUARIO);
    }
}
