/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcionario;

import controle.Numero;
import controle.Productodao;
import controle.Sobredao;
import controle.Vendadao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class Tela extends javax.swing.JFrame implements ActionListener {

    private DefaultTableModel modelo;
    private DecimalFormat mt;
    private ArrayList a;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        txtcontacto.setDocument(new Numero());
        setExtendedState(MAXIMIZED_BOTH);
        mt = new DecimalFormat("#,###,##0.00 Mt");
        modelo = (DefaultTableModel) jTableproductos.getModel();
        a = new ArrayList();

        //Mostrar o ano
        Calendar cal = Calendar.getInstance();
        Ano.setText("BControl © " + cal.get(Calendar.YEAR));
        limpar();

    }

    public void temporizador() {
        int delay = 10000;   // delay de 10 seg.
        int interval = 15000;  // intervalo de 15 seg.
        Timer timer = new Timer();

        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                // colocar tarefas aqui ...

                visualizar();

            }
        }, delay, interval);

    }

    public void limpar() {
        visualizar();
        txtnome.setText("");
        txtcontacto.setText("");
    }

    public void visualizar() {
        modelo.setNumRows(0);
        a = new ArrayList<>();
        Productodao ndao = new Productodao();
        ndao.visualizarcesto().forEach((n) -> {
            a.add(n);
            modelo.addRow(new Object[]{
                n.getCodigo(),
                n.getNome(),
                n.getQuantidade(),
                mt.format(n.getPreco())
            });
        });
        double t = ndao.total();
        double i = t * 0.17;
        double s = t - i;
        total.setText(mt.format(t));
        iva.setText(mt.format(i));
        subtotal.setText(mt.format(s));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conteudo = new javax.swing.JPanel();
        Separador = new javax.swing.JSeparator();
        Nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnremover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproductos = new javax.swing.JTable();
        btnproductos = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        Venda = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnpagar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        subtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        Rodape = new javax.swing.JToolBar();
        Ano = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenuBControl = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemVendas = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuItemEditarSenha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Conteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Conteudo.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1370, 10));

        Nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nome.setText("Nome");
        Conteudo.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 940, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Funcionário:");
        Conteudo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnremover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/apagar.png"))); // NOI18N
        btnremover.setText("Remover");
        btnremover.setPreferredSize(new java.awt.Dimension(80, 30));
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });
        Conteudo.add(btnremover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 50));

        jTableproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproductosMouseClicked(evt);
            }
        });
        jTableproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableproductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproductos);
        if (jTableproductos.getColumnModel().getColumnCount() > 0) {
            jTableproductos.getColumnModel().getColumn(0).setResizable(false);
            jTableproductos.getColumnModel().getColumn(0).setPreferredWidth(11);
            jTableproductos.getColumnModel().getColumn(2).setResizable(false);
            jTableproductos.getColumnModel().getColumn(2).setPreferredWidth(11);
        }

        Conteudo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1340, 410));

        btnproductos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mercadoria.png"))); // NOI18N
        btnproductos.setText("Productos");
        btnproductos.setPreferredSize(new java.awt.Dimension(80, 30));
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        Conteudo.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, 120, 50));

        btnsair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsair.setText("Sair");
        btnsair.setPreferredSize(new java.awt.Dimension(125, 25));
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        Conteudo.add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 120, -1));

        getContentPane().add(Conteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 530));

        Venda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Venda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nome do Cliente:");
        Venda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Venda.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contacto do Cliente:");
        Venda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        txtcontacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Venda.add(txtcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("0.00 Mt");
        Venda.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 290, 40));

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncancelar.setText("Nova Venda");
        btncancelar.setPreferredSize(new java.awt.Dimension(80, 30));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        Venda.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 120, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total:");
        Venda.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 90, -1));

        btnpagar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pagar.png"))); // NOI18N
        btnpagar.setText("Pagar");
        btnpagar.setPreferredSize(new java.awt.Dimension(80, 30));
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        Venda.add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 90, 50));

        btnimprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/recibo.png"))); // NOI18N
        btnimprimir.setText("Recibo");
        btnimprimir.setEnabled(false);
        btnimprimir.setPreferredSize(new java.awt.Dimension(80, 30));
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        Venda.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 100, 50));

        subtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtotal.setText("0.00 Mt");
        Venda.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 290, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SubTotal:");
        Venda.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("IVA (17%):");
        Venda.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 90, -1));

        iva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iva.setText("0.00 Mt");
        Venda.add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 290, 40));

        getContentPane().add(Venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1370, 170));

        Rodape.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rodape.setRollover(true);

        Ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rodape.add(Ano);

        getContentPane().add(Rodape, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1370, 30));

        jMenuBControl.setText("BControl");

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuBControl.add(jMenuItemFechar);

        Menu.add(jMenuBControl);

        jMenuRelatorio.setText("Relatório");

        jMenuItemProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mercadoria.png"))); // NOI18N
        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemProductos);

        jMenuItemVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pagar.png"))); // NOI18N
        jMenuItemVendas.setText("Vendas");
        jMenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemVendas);

        Menu.add(jMenuRelatorio);

        jMenuFuncionario.setText("Funcionário");

        jMenuItemEditarSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/editar.png"))); // NOI18N
        jMenuItemEditarSenha.setText("Editar Senha");
        jMenuItemEditarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarSenhaActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemEditarSenha);
        jMenuFuncionario.add(jSeparator1);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemSair);

        Menu.add(jMenuFuncionario);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        Inicio Inicio = new Inicio();
        Inicio.setVisible(true);

        Productodao udao = new Productodao();
        if (btnpagar.isEnabled() == false) {

            DefaultTableModel modelo = (DefaultTableModel) jTableproductos.getModel();
            try {
                udao.limparcesto();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (btnpagar.isEnabled() == true) {
            try {
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    udao.quantidade((String) jTableproductos.getValueAt(i, 0), (int) jTableproductos.getValueAt(i, 2));
                }
                udao.limparcesto();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

        Productodao udao = new Productodao();
        if (btnpagar.isEnabled() == false) {

            DefaultTableModel modelo = (DefaultTableModel) jTableproductos.getModel();
            try {
                udao.limparcesto();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (btnpagar.isEnabled() == true) {
            try {
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    udao.quantidade((String) jTableproductos.getValueAt(i, 0), (int) jTableproductos.getValueAt(i, 2));
                }
                udao.limparcesto();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        limpar();
        btncancelar.setEnabled(true);
        btnremover.setEnabled(true);
        btnpagar.setEnabled(true);
        btnproductos.setEnabled(true);
        btnimprimir.setEnabled(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        if (jTableproductos.getRowCount() >= 1) {
            Productodao udao = new Productodao();
            Vendadao vdao = new Vendadao();

            if (txtnome.getText().length() > 80 || txtcontacto.getText().length() > 9) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha o Nome com 80 caracteres no máximo e/ou Contacto do cliente com 9 carascteres no máximo.", "Campo em Branco.", JOptionPane.WARNING_MESSAGE);
            } else if (txtnome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha o Nome do cliente.", "Campo em Branco.", JOptionPane.WARNING_MESSAGE);
            } else if (txtcontacto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha o Contacto do cliente.", "Campo em Branco.", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    if (vdao.vender() && vdao.funcionario(Nome.getText(), txtnome.getText().toLowerCase(), Integer.parseInt(txtcontacto.getText()))) {

                        btnremover.setEnabled(false);
                        btnproductos.setEnabled(false);
                        btnpagar.setEnabled(false);
                        btnimprimir.setEnabled(true);
                        JOptionPane.showMessageDialog(null, "Venda efectuada com sucesso.", "Obrigado", JOptionPane.DEFAULT_OPTION);

                    } else {
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro ao efectuar a venda.", "Desculpa", JOptionPane.WARNING_MESSAGE);
                    }

                } catch (Exception ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Não há productos para Pagar.", "Desculpa", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnpagarActionPerformed

    private void jTableproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableproductosKeyReleased

    }//GEN-LAST:event_jTableproductosKeyReleased

    private void jTableproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproductosMouseClicked

    }//GEN-LAST:event_jTableproductosMouseClicked

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
        if (jTableproductos.getSelectedRow() != -1) {
            Productodao dao = new Productodao();
            if (dao.quantidade((String) jTableproductos.getValueAt(jTableproductos.getSelectedRow(), 0), (int) jTableproductos.getValueAt(jTableproductos.getSelectedRow(), 2))) {
                dao.apagar((String) jTableproductos.getValueAt(jTableproductos.getSelectedRow(), 0));
                limpar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione a linha do Producto que pretende remover.", "Producto não selecionado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnremoverActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        Sobredao ndao = new Sobredao();
        ndao.visualizar().forEach((n) -> {
            imprimirRecibo(modelo, txtnome.getText(), total.getText(), Nome.getText(), subtotal.getText(), iva.getText(), n.getNome(), n.getNuit() , n.getContacto() , n.getEndereco());
        });
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        temporizador();
        Producto Producto = new Producto();
        Producto.setVisible(true);
        Producto.pack();
        Producto.setLocationRelativeTo(null);
        Producto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnproductosActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        if (jTableproductos.getRowCount() >= 1) {
            Productodao udao = new Productodao();
            DefaultTableModel modelo = (DefaultTableModel) jTableproductos.getModel();
            try {
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    udao.quantidade((String) jTableproductos.getValueAt(i, 0), (int) jTableproductos.getValueAt(i, 2));
                }
                udao.limparcesto();
                limpar();
            } catch (Exception ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        Inicio Inicio = new Inicio();
        Inicio.setVisible(true);
        Productodao udao = new Productodao();
        try {
            for (int i = 0; i < modelo.getRowCount(); i++) {
                udao.quantidade((String) jTableproductos.getValueAt(i, 0), (int) jTableproductos.getValueAt(i, 2));
            }
            udao.limparcesto();
            limpar();
        } catch (Exception ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemEditarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarSenhaActionPerformed
        Senha Senha = new Senha();
        Senha.setVisible(true);
        Senha.pack();
        Senha.setLocationRelativeTo(null);
        Senha.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Senha.nome(Nome.getText());
    }//GEN-LAST:event_jMenuItemEditarSenhaActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        Productos Producto = new Productos();
        Producto.setVisible(true);
        Producto.pack();
        Producto.setLocationRelativeTo(null);
        Producto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasActionPerformed
        Vendas Venda = new Vendas();
        Venda.setVisible(true);
        Venda.pack();
        Venda.setLocationRelativeTo(null);
        Venda.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ano;
    private javax.swing.JPanel Conteudo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel Nome;
    private javax.swing.JToolBar Rodape;
    private javax.swing.JSeparator Separador;
    private javax.swing.JPanel Venda;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnpagar;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnremover;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel iva;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuBControl;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItemEditarSenha;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVendas;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTableproductos;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtcontacto;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
 public void nome(String USUARIO) {
        Nome.setText(USUARIO);
    }

    public void imprimirRecibo(DefaultTableModel modelo, String cliente, String total, String funcionario, String subtotal, String iva, String loja, int nuit, int contacto, String endereco) {
        //data
        SimpleDateFormat dataF = new SimpleDateFormat("dd/MM/yyyy");
        String data = dataF.format(new Date());

        //hora
        SimpleDateFormat horaF = new SimpleDateFormat("H:mm - a");
        String hora = horaF.format(new Date());

        String conteudo = "";
        for (int i = 0; i < a.size(); i++) {
            conteudo += a.get(i).toString() + "\n\r";
        }

        this.imprimir(loja + "\n\r"
                + "Contacto: " + contacto + "\n\r"
                + "Nuit: " + nuit + "\n\r"
                + endereco + "\n\r"
                + "Funcionario: " + funcionario + "\n\r"
                + "\n\r"
                + "   Producto    Qtd     Preco\n\r"
                + "---------------------------------\n\r"
                + conteudo
                + "---------------------------------\n\r"
                + "SubTotal: " + subtotal + "\n\r"
                + "IVA: " + iva + "\n\r"
                + "Total: " + total + "\n\r"
                + "=================================\n\r"
                + "Cliente: " + cliente + "\n\r"
                + data + " | " + hora + "\n\r"
                + "\n\r \n\r"
                + "Artigos em promocao, nao se\n\r"
                + "efectuam trocas."
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\n\r"
                + "\f"
        );
    }

    public void imprimir(String texto) {
        try {
            InputStream is = new ByteArrayInputStream(texto.getBytes());
            DocFlavor docf = DocFlavor.INPUT_STREAM.AUTOSENSE;
            SimpleDoc sd = new SimpleDoc(is, docf, null);
            PrintService ps = PrintServiceLookup.lookupDefaultPrintService();
            //pegar a impressora padrao
            PrintRequestAttributeSet pras = new HashPrintRequestAttributeSet();
            pras.add(new JobName("Impressao", null));
            pras.add(OrientationRequested.PORTRAIT);
            pras.add(MediaSizeName.ISO_A4);
            //imformar o tipo de folha
            DocPrintJob dpj = ps.createPrintJob();
            try {
                dpj.print(sd, (PrintRequestAttributeSet) pras);
            } catch (PrintException e) {
                JOptionPane.showMessageDialog(null, "Não foi possível imprimir o recibo!", "Desculpa", JOptionPane.ERROR_MESSAGE);
            }
            is.close();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Adicionar adicionar = new Adicionar();
        if (e.getSource() == adicionar.getBtnadicionar()) {

            System.out.println("jngbhk");
        }
    }

}
